const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');

exports.handler = async (event, context) => {
  // Handle CORS
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
      },
      body: '',
    };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }

  try {
    const { content, filename, metadata = {} } = JSON.parse(event.body);

    if (!content) {
      return {
        statusCode: 400,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ error: 'Missing content parameter' }),
      };
    }

    // Parse content into paragraphs
    const lines = content.split('\n').filter(line => line.trim() !== '');
    const children = [];

    // Add claim information header if provided
    if (metadata.claim_number || metadata.policyholder_name || metadata.policy_number || metadata.date_of_loss) {
      const headerLines = [];
      if (metadata.claim_number) headerLines.push(`Claim #: ${metadata.claim_number}`);
      if (metadata.policyholder_name) headerLines.push(`Policyholder: ${metadata.policyholder_name}`);
      if (metadata.policy_number) headerLines.push(`Policy #: ${metadata.policy_number}`);
      if (metadata.date_of_loss) headerLines.push(`Date of Loss: ${metadata.date_of_loss}`);
      headerLines.push(`Generated: ${new Date().toLocaleDateString()}`);

      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: headerLines.join(' | '),
              size: 20,
              color: '333333'
            })
          ],
          spacing: { after: 300 }
        })
      );
    }

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      
      if (line === '') continue;

      // Check if line is a heading (all caps or starts with specific patterns)
      if (line === line.toUpperCase() && line.length > 3 && !line.includes('$') && !line.includes(':')) {
        children.push(
          new Paragraph({
            text: line,
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 200, before: 200 },
          })
        );
      } else if (line.includes(':') && !line.includes('$')) {
        // Subheading
        children.push(
          new Paragraph({
            text: line,
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 150, before: 150 },
          })
        );
      } else {
        // Regular paragraph
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: line,
                size: 24, // 12pt
              }),
            ],
            spacing: { after: 100 },
          })
        );
      }
    }

    // Add footer paragraphs
    children.push(
      new Paragraph({
        text: '',
        spacing: { before: 400 }
      })
    );
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by Claim Command Pro • Professional Insurance Claim Management',
            size: 16,
            color: '999999'
          })
        ],
        alignment: 'center',
        spacing: { after: 50 }
      })
    );
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: 'Not for redistribution • Confidential claim documentation',
            size: 14,
            color: 'AAAAAA',
            italics: true
          })
        ],
        alignment: 'center'
      })
    );

    // Create document
    const doc = new Document({
      creator: 'Claim Command Pro',
      title: metadata.title || 'Claim Document',
      description: 'Generated by Claim Command Pro',
      sections: [
        {
          properties: {},
          children: children,
        },
      ],
    });

    // Generate DOCX buffer
    const buffer = await Packer.toBuffer(doc);

    // Convert to base64
    const base64Docx = buffer.toString('base64');

    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${filename || 'document.docx'}"`,
        'Content-Length': buffer.length.toString(),
      },
      body: base64Docx,
      isBase64Encoded: true,
    };

  } catch (error) {
    console.error('Error generating DOCX:', error);
    
    return {
      statusCode: 500,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        error: 'Failed to generate DOCX',
        details: error.message,
      }),
    };
  }
};
