const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType
} = require('docx');

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Allow-Methods': 'POST, OPTIONS'
};

function buildMetadataHeader(metadata) {
  if (!metadata.claim_number && !metadata.policyholder_name && !metadata.policy_number && !metadata.date_of_loss) {
    return [];
  }

  const headerLines = [];
  if (metadata.claim_number) headerLines.push(`Claim #: ${metadata.claim_number}`);
  if (metadata.policyholder_name) headerLines.push(`Policyholder: ${metadata.policyholder_name}`);
  if (metadata.policy_number) headerLines.push(`Policy #: ${metadata.policy_number}`);
  if (metadata.date_of_loss) headerLines.push(`Date of Loss: ${metadata.date_of_loss}`);
  if (metadata.insurer) headerLines.push(`Insurer: ${metadata.insurer}`);
  headerLines.push(`Generated: ${new Date().toLocaleDateString()}`);

  return [
    new Paragraph({
      children: [
        new TextRun({
          text: headerLines.join(' | '),
          size: 20,
          color: '333333'
        })
      ],
      spacing: { after: 300 }
    })
  ];
}

function buildFooterParagraphs() {
  return [
    new Paragraph({ text: '', spacing: { before: 400 } }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by Claim Command Pro • Professional Insurance Claim Management',
          size: 16,
          color: '999999'
        })
      ],
      alignment: 'center',
      spacing: { after: 50 }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Not for redistribution • Confidential claim documentation',
          size: 14,
          color: 'AAAAAA',
          italics: true
        })
      ],
      alignment: 'center'
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'This document is informational only and does not constitute legal or insurance advice.',
          size: 14,
          color: 'AAAAAA',
          italics: true
        })
      ],
      alignment: 'center',
      spacing: { before: 100 }
    })
  ];
}

function buildTableParagraph(tableData) {
  const head = Array.isArray(tableData.head) ? tableData.head : [];
  const body = Array.isArray(tableData.body) ? tableData.body : [];
  const rows = head.length ? [head, ...body] : body;

  if (!rows.length) return null;

  return new Table({
    rows: rows.map((row, rowIndex) => new TableRow({
      children: row.map(cell => new TableCell({
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: String(cell ?? ''),
                size: 20,
                bold: rowIndex === 0
              })
            ]
          })
        ],
        width: {
          size: Math.floor(100 / row.length),
          type: WidthType.PERCENTAGE
        }
      }))
    })),
    width: { size: 100, type: WidthType.PERCENTAGE }
  });
}

function buildStructuredChildren(structured, metadata) {
  const children = [];

  if (structured.title) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: structured.title,
            bold: true,
            size: 32
          })
        ],
        heading: HeadingLevel.TITLE,
        spacing: { after: 200 }
      })
    );
  }

  if (structured.subtitle) {
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: structured.subtitle,
            size: 22,
            color: '64748B'
          })
        ],
        spacing: { after: 300 }
      })
    );
  }

  children.push(...buildMetadataHeader(metadata));

  for (const section of structured.sections || []) {
    if (section.heading && section.heading !== '---') {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: section.heading,
              bold: true,
              size: 26
            })
          ],
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 }
        })
      );
    } else if (section.heading === '---') {
      children.push(new Paragraph({ text: '', spacing: { before: 120 } }));
    }

    if (section.body) {
      String(section.body).split('\n').forEach(line => {
        const trimmed = line.trim();
        if (!trimmed) return;
        children.push(
          new Paragraph({
            children: [new TextRun({ text: trimmed, size: 24 })],
            spacing: { after: 100 }
          })
        );
      });
    }

    if (section.table) {
      const table = buildTableParagraph(section.table);
      if (table) {
        children.push(table);
        children.push(new Paragraph({ text: '', spacing: { after: 200 } }));
      }
    }
  }

  children.push(...buildFooterParagraphs());
  return children;
}

function buildPlainTextChildren(content, metadata) {
  const lines = content.split('\n').filter(line => line.trim() !== '');
  const children = [...buildMetadataHeader(metadata)];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === '') continue;

    if (line === line.toUpperCase() && line.length > 3 && !line.includes('$') && !line.includes(':')) {
      children.push(
        new Paragraph({
          text: line,
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200, before: 200 }
        })
      );
    } else if (line.includes(':') && !line.includes('$')) {
      children.push(
        new Paragraph({
          text: line,
          heading: HeadingLevel.HEADING_2,
          spacing: { after: 150, before: 150 }
        })
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 24 })],
          spacing: { after: 100 }
        })
      );
    }
  }

  children.push(...buildFooterParagraphs());
  return children;
}

async function buildDocxBuffer({ content, structured, metadata }) {
  const children = structured
    ? buildStructuredChildren(structured, metadata)
    : buildPlainTextChildren(content, metadata);

  const doc = new Document({
    creator: 'Claim Command Pro',
    title: metadata.title || structured?.title || 'Claim Document',
    description: 'Generated by Claim Command Pro',
    sections: [{ properties: {}, children }]
  });

  return Packer.toBuffer(doc);
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers: CORS_HEADERS, body: '' };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }

  try {
    const { content, structured, filename, metadata = {} } = JSON.parse(event.body || '{}');

    if (!content && !structured) {
      return {
        statusCode: 400,
        headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Missing content or structured parameter' })
      };
    }

    const buffer = await buildDocxBuffer({ content, structured, metadata });
    const base64Docx = buffer.toString('base64');
    const safeName = (filename || 'document.docx').replace(/[^\w.\- ]+/g, '_');

    return {
      statusCode: 200,
      headers: {
        ...CORS_HEADERS,
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${safeName}"`,
        'Content-Length': buffer.length.toString()
      },
      body: base64Docx,
      isBase64Encoded: true
    };
  } catch (error) {
    console.error('Error generating DOCX:', error);

    return {
      statusCode: 500,
      headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        error: 'Failed to generate DOCX',
        details: error.message
      })
    };
  }
};
